version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    target_branch: "dev"
    default_reviewers:
      - "achamely"
      - "germanf"
    allowed_updates:
      - match:
          update_type: "security"
